In [21]:
from tensorflow.keras.preprocessing.text import one_hot
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [12]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'i am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
voc_size=10000

In [23]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[8172, 5452, 9484, 5317],
 [8172, 5452, 9484, 562],
 [8172, 8277, 9484, 194],
 [7194, 438, 3431, 3316, 3060],
 [7194, 438, 3431, 3316, 5507],
 [4751, 8172, 5259, 9484, 2661],
 [2453, 8923, 2280, 3316]]

In [50]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [51]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 8172 5452 9484 5317]
 [   0    0    0    0 8172 5452 9484  562]
 [   0    0    0    0 8172 8277 9484  194]
 [   0    0    0 7194  438 3431 3316 3060]
 [   0    0    0 7194  438 3431 3316 5507]
 [   0    0    0 4751 8172 5259 9484 2661]
 [   0    0    0    0 2453 8923 2280 3316]]


In [52]:
dim=10

In [63]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile(optimizer='adam', loss='mse')
model.summary()

/Users/pratyushgupta/anaconda3/envs/tf/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_18 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
embedded_doc[0]

array([   0,    0,    0,    0, 8172, 5452, 9484, 5317], dtype=int32)

In [72]:
model.predict(embedded_doc)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[-0.00704427,  0.00275629,  0.02128354, -0.01884671,  0.03700609,
         0.02839407,  0.01668103, -0.0469316 ,  0.03529974, -0.03191765],
       [-0.00704427,  0.00275629,  0.02128354, -0.01884671,  0.03700609,
         0.02839407,  0.01668103, -0.0469316 ,  0.03529974, -0.03191765],
       [-0.00704427,  0.00275629,  0.02128354, -0.01884671,  0.03700609,
         0.02839407,  0.01668103, -0.0469316 ,  0.03529974, -0.03191765],
       [-0.00704427,  0.00275629,  0.02128354, -0.01884671,  0.03700609,
         0.02839407,  0.01668103, -0.0469316 ,  0.03529974, -0.03191765],
       [-0.0044889 ,  0.04595559,  0.00387645, -0.01735519, -0.04043446,
         0.0281035 ,  0.02780077, -0.03798295, -0.01464704,  0.0317123 ],
       [ 0.04593916,  0.04338293, -0.04968268, -0.01788504, -0.0086145 ,
         0.02546049,  0.02088633, -0.03907102,  0.00659368, -0.02672849],
       [ 0.02053061, -0.00218581,  0.04084784, -0.03921048,  0.00357207,
        -0.00982741, -0.00581085,  0.00384239